// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xydsolvrbsimwltkchow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5ZHNvbHZyYnNpbXdsdGtjaG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzE3MzUsImV4cCI6MjA2NTcwNzczNX0.UhG6bbpfBwHLtBRWAoCNJOANZQCaxkqD8A91rwzT2iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});